// Code generated by go-swagger; DO NOT EDIT.

package forecast_calculation_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewForecastCalculationServiceExecuteForecastCalculationParams creates a new ForecastCalculationServiceExecuteForecastCalculationParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewForecastCalculationServiceExecuteForecastCalculationParams() *ForecastCalculationServiceExecuteForecastCalculationParams {
	return &ForecastCalculationServiceExecuteForecastCalculationParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewForecastCalculationServiceExecuteForecastCalculationParamsWithTimeout creates a new ForecastCalculationServiceExecuteForecastCalculationParams object
// with the ability to set a timeout on a request.
func NewForecastCalculationServiceExecuteForecastCalculationParamsWithTimeout(timeout time.Duration) *ForecastCalculationServiceExecuteForecastCalculationParams {
	return &ForecastCalculationServiceExecuteForecastCalculationParams{
		timeout: timeout,
	}
}

// NewForecastCalculationServiceExecuteForecastCalculationParamsWithContext creates a new ForecastCalculationServiceExecuteForecastCalculationParams object
// with the ability to set a context for a request.
func NewForecastCalculationServiceExecuteForecastCalculationParamsWithContext(ctx context.Context) *ForecastCalculationServiceExecuteForecastCalculationParams {
	return &ForecastCalculationServiceExecuteForecastCalculationParams{
		Context: ctx,
	}
}

// NewForecastCalculationServiceExecuteForecastCalculationParamsWithHTTPClient creates a new ForecastCalculationServiceExecuteForecastCalculationParams object
// with the ability to set a custom HTTPClient for a request.
func NewForecastCalculationServiceExecuteForecastCalculationParamsWithHTTPClient(client *http.Client) *ForecastCalculationServiceExecuteForecastCalculationParams {
	return &ForecastCalculationServiceExecuteForecastCalculationParams{
		HTTPClient: client,
	}
}

/*
ForecastCalculationServiceExecuteForecastCalculationParams contains all the parameters to send to the API endpoint

	for the forecast calculation service execute forecast calculation operation.

	Typically these are written to a http.Request.
*/
type ForecastCalculationServiceExecuteForecastCalculationParams struct {

	// ID1.
	//
	// Format: int64
	ID1 string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the forecast calculation service execute forecast calculation params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ForecastCalculationServiceExecuteForecastCalculationParams) WithDefaults() *ForecastCalculationServiceExecuteForecastCalculationParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the forecast calculation service execute forecast calculation params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ForecastCalculationServiceExecuteForecastCalculationParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the forecast calculation service execute forecast calculation params
func (o *ForecastCalculationServiceExecuteForecastCalculationParams) WithTimeout(timeout time.Duration) *ForecastCalculationServiceExecuteForecastCalculationParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the forecast calculation service execute forecast calculation params
func (o *ForecastCalculationServiceExecuteForecastCalculationParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the forecast calculation service execute forecast calculation params
func (o *ForecastCalculationServiceExecuteForecastCalculationParams) WithContext(ctx context.Context) *ForecastCalculationServiceExecuteForecastCalculationParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the forecast calculation service execute forecast calculation params
func (o *ForecastCalculationServiceExecuteForecastCalculationParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the forecast calculation service execute forecast calculation params
func (o *ForecastCalculationServiceExecuteForecastCalculationParams) WithHTTPClient(client *http.Client) *ForecastCalculationServiceExecuteForecastCalculationParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the forecast calculation service execute forecast calculation params
func (o *ForecastCalculationServiceExecuteForecastCalculationParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID1 adds the iD1 to the forecast calculation service execute forecast calculation params
func (o *ForecastCalculationServiceExecuteForecastCalculationParams) WithID1(iD1 string) *ForecastCalculationServiceExecuteForecastCalculationParams {
	o.SetID1(iD1)
	return o
}

// SetID1 adds the id1 to the forecast calculation service execute forecast calculation params
func (o *ForecastCalculationServiceExecuteForecastCalculationParams) SetID1(iD1 string) {
	o.ID1 = iD1
}

// WriteToRequest writes these params to a swagger request
func (o *ForecastCalculationServiceExecuteForecastCalculationParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id_1
	if err := r.SetPathParam("id_1", o.ID1); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
